-- ============================================================================
-- 0007_storage.sql
-- Storage buckets: avatars (public), materials (pdfs/mapas mentais, private,
-- served through signed URLs) and lesson-thumbnails (public).
-- ============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', true, 5242880, array['image/png', 'image/jpeg', 'image/webp']),
  ('lesson-thumbnails', 'lesson-thumbnails', true, 5242880, array['image/png', 'image/jpeg', 'image/webp']),
  ('materials', 'materials', false, 52428800, array['application/pdf', 'image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do nothing;

-- ----------------------------------------------------------------------------
-- avatars: any authenticated user can read (public bucket); a user may only
-- write/delete inside a folder named after their own uid, e.g. `${uid}/photo.png`.
-- ----------------------------------------------------------------------------
create policy "avatars_public_read"
  on storage.objects for select
  using (bucket_id = 'avatars');

create policy "avatars_owner_write"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "avatars_owner_update"
  on storage.objects for update to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "avatars_owner_delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- ----------------------------------------------------------------------------
-- lesson-thumbnails: public read, admin-only write.
-- ----------------------------------------------------------------------------
create policy "lesson_thumbnails_public_read"
  on storage.objects for select
  using (bucket_id = 'lesson-thumbnails');

create policy "lesson_thumbnails_admin_write"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'lesson-thumbnails' and public.is_admin());

create policy "lesson_thumbnails_admin_update"
  on storage.objects for update to authenticated
  using (bucket_id = 'lesson-thumbnails' and public.is_admin());

create policy "lesson_thumbnails_admin_delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'lesson-thumbnails' and public.is_admin());

-- ----------------------------------------------------------------------------
-- materials: private bucket. Admins manage files; any authenticated student
-- may read (download URLs are still short-lived signed URLs generated by the
-- backend/Edge Function, and the `materials` table RLS additionally gates
-- premium content by subscription status).
-- ----------------------------------------------------------------------------
create policy "materials_authenticated_read"
  on storage.objects for select to authenticated
  using (bucket_id = 'materials');

create policy "materials_admin_write"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'materials' and public.is_admin());

create policy "materials_admin_update"
  on storage.objects for update to authenticated
  using (bucket_id = 'materials' and public.is_admin());

create policy "materials_admin_delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'materials' and public.is_admin());
